[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundle = true

[context.production.environment]
  # This "passes" the variables into the background function environment
  VITE_FIREBASE_API_KEY = "VITE_FIREBASE_API_KEY"
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"