[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # In 2026, node_bundle must be defined as an object
  [functions.node_bundle]
    node_bundler = "esbuild"
    external_node_modules = ["firebase", "node-fetch"]

[context.production.environment]
  VITE_FIREBASE_API_KEY = "VITE_FIREBASE_API_KEY"
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"